export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_DATA = 'AUTH_LOGIN_DATA';
export const AUTH_LOGIN_HTTP_STATUS = 'AUTH_LOGIN_HTTP_STATUS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_OTP_START = 'AUTH_OTP_START';
export const AUTH_OTP_DATA = 'AUTH_OTP_DATA';
export const AUTH_OTP_HTTP_STATUS = 'AUTH_OTP_HTTP_STATUS';

export const AUTH_REGISTER_DATA = 'AUTH_REGISTER_DATA';
export const AUTH_REGISTER_HTTP_STATUS = 'AUTH_REGISTER_HTTP_STATUS';

export const GET_STATES = 'GET_STATES';
export const GET_CITIES = 'GET_CITIES';

export const GET_APPLY_LOAN_DATA = 'GET_APPLY_LOAN_DATA';
export const CLEAR_APPLY_LOAN_DATA = 'CLEAR_APPLY_LOAN_DATA';

